# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lghDMrukZ-t4XEeXWuBmlOWOazixAduR
"""

!pip install pymongo
from pymongo import MongoClient

import pandas as pd
import matplotlib.pyplot as plt

def chartes(file_path):
  df = pd.read_json(file_path)
  df.drop(index=0, inplace=True)
  fg = ["bbox","image_path","_id","test"]
  df.drop(columns=fg, inplace=True)
  df['timestand_date_str'] = df['timestand'].apply(lambda x: x['$date'] if isinstance(x, dict) and '$date' in x else None)
  df['timestand_datetime'] = pd.to_datetime(df['timestand_date_str'])
  df["seconds"] = df['timestand_datetime'].dt.second
  df["mintes"] = df["timestand_datetime"].dt.minute
  bar_cahrt(df)
  line_chart(df)

def bar_cahrt(df):
  plt.figure(figsize=(10, 6))
  class_counts = df['class'].value_counts()
  print(class_counts)
  print(class_counts.index)
  print(class_counts.values)
  plt.bar(class_counts.index, class_counts.values)
  plt.xlabel('Class')
  plt.ylabel('Count')
  plt.title('Distribution of Classes')
  plt.show()

def line_chart(df):
  lister = df["class"].unique()
  for lit in range(len(lister)-1):
    ty =df[df["class"] == lister[lit]]
    ty = ty.sort_values(by="mintes", ascending=False)
    countesh = ty['mintes'].value_counts()
    plt.figure(figsize=(10, 6))
    sorted_countes = countesh.sort_index()
    print(  sorted_countes.index)
    print(sorted_countes.values)
    plt.plot(sorted_countes.index, sorted_countes.values)
    plt.ylabel('number of vehical ')
    plt.xlabel('Minute')
    plt.title('Vehicle Count by Minute')
    plt.grid(True)
    plt.show()

chartes(r"/content/Pavilion_mangment_dataset.vehical_live1.json")