# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEOT6AW88rIBG2C3b4Nlr7x_HuEMqQMU
"""

!pip install ultralytics
!pip install roboflow

from google.colab import files
uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

!unzip "vehical.v1i.yolov8.zip" -d /content/vehical_weight_yolov8_data

from ultralytics import YOLO

model = YOLO('yolov8n.pt')  # nano (fastest)

model.train(
    data= '/content/vehical_weight_yolov8_data/vehical weight.v1i.yolov8/data.yaml',
    epochs=50,
    imgsz=640,
    batch=16
)

!ls runs/detect/train

model.predict('/content/vehical_weight_yolov8_data/vehical weight.v1i.yolov8/test/images')

from google.colab import files
files.download('runs/detect/train2/weights/best.pt')

